# @package _global_

defaults:
  - /pretraining_new
  - override /object_class: bowl
  - _self_

benchmark:
  dataset_root: /data/ndf_original/data/

resources:
  num_workers: 16

training:
  epochs: 3
  batch_size: 8
  check_val_every_n_epoch: 1
  log_every_n_steps: 100

emb_nn: "dgcnn"
